# Generated by Django 5.1.2 on 2024-11-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
