# Generated by Django 5.1.2 on 2024-11-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='offer_details',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_version',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='salary_expectation',
            field=models.DecimalField(blank=True, decimal_places=2, default='Not Specified', max_digits=10, null=True),
        ),
    ]
