# Generated by Django 5.1.2 on 2024-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_remove_jobapplication_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company_website',
            field=models.URLField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_posting_url',
            field=models.URLField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Offer Received', 'Offer Received'), ('Rejected', 'Rejected')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='work_setup',
            field=models.CharField(choices=[('Full FTF', 'Full FTF'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='N/A', max_length=50),
        ),
    ]
