# Generated by Django 5.1.2 on 2024-11-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_jobapplication_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_posting_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='salary_expectation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Offer Received', 'Offer Received'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='work_setup',
            field=models.CharField(blank=True, choices=[('Full FTF', 'Full FTF'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=50, null=True),
        ),
    ]
