# Generated by Django 5.1.2 on 2024-11-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_jobapplication_company_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='date_interviewed',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='salary_expectation',
        ),
    ]
