# Generated by Django 5.1.2 on 2024-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action_type',
            field=models.CharField(choices=[('submitted_application', 'Submitted Application'), ('interview_scheduled', 'Scheduled Interview'), ('note_added', 'Added Note'), ('status_changed', 'Changedd Status')], max_length=30),
        ),
    ]
