# Generated by Django 5.1.2 on 2024-11-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_useractivity_scheduled_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action_type',
            field=models.CharField(choices=[('submitted_application', 'Submitted Application'), ('interview_scheduled', 'Scheduled Interview'), ('status_changed', 'Changed Status')], max_length=30),
        ),
    ]
