# Generated by Django 5.1.2 on 2024-11-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_jobapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
