# Generated by Django 5.1.2 on 2024-11-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_jobapplication_interview_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_via',
        ),
    ]
