# Generated by Django 5.1.2 on 2024-11-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_remove_jobapplication_applied_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
