# Generated by Django 5.1.2 on 2024-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_alter_reminders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
